update code

diff --git a/.github/workflows/hello-world.yml b/.github/workflows/hello-world.yml
--- a/.github/workflows/hello-world.yml
+++ b/.github/workflows/hello-world.yml
@@ -16,8 +16,11 @@ jobs:
         id: parse-config
         run: |
           matrix=$(yq eval -o=json '.images' docker-config.yaml | jq -c '.')
+          if [[ -z "$matrix" ]]; then
+            echo "Error: Matrix is empty. Check docker-config.yaml."
+            exit 1
+          fi
           printf "matrix=%s\n" "$matrix" >> "$GITHUB_OUTPUT"
-
   docker-build:
     needs: parse-config
     runs-on: self-hosted
